TP2_exercice1/exercice1: TP2_exercice1/exercice1.c
	gcc TP2_exercice1/exercice1.c -o TP2_exercice1/exercice1
	
TP2_exercice2/exercice2: TP2_exercice2/exercice2.c
	gcc TP2_exercice2/exercice2.c -o TP2_exercice2/exercice2
	
TP2_exercice3/exercice3: TP2_exercice3/exercice3.c
	gcc TP2_exercice2/exercice3.c -o TP2_exercice2/exercice3
